In [1]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

In [25]:
import cv2

#웹캠에서 영상을 읽어온다
cap = cv2.VideoCapture(0)
cap.set(3, 640) #WIDTH
cap.set(4, 480) #HEIGHT

#얼굴 인식 캐스케이드 파일 읽는다
face_cascade = cv2.CascadeClassifier('haarcascades\\haarcascade_frontalface_default.xml')
# face_cascade = cv2.CascadeClassifier('C:\\Users\\LSW\\Desktop\\Smart_mirror\\lg-2nd\\haarcascades\\haarcascade_frontalface_default.xml')

while(True):
    # frame 별로 capture 한다
    ret, frame = cap.read()
    feame = cv2.imread('./face.jpg')
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=2.08, minNeighbors=5)

    #인식된 얼굴 갯수를 출력
    if(len(faces)>0):
        print(len(faces))

        # 인식된 얼굴에 사각형을 출력한다
        for (x,y,w,h) in faces:
             cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)

    #화면에 출력한다
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [ ]:
cap.release()
cv2.destroyAllWindows()

In [27]:
import cv2

cascadefile = 'haarcascades/haarcascade_frontalface_default.xml'

img = cv2.imread('./face.jpg')
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cascade = cv2.CascadeClassifier(cascadefile)
facelist = cascade.detectMultiScale(imgray,
                                    scaleFactor=2.08,
                                    minNeighbors=1)

print(facelist)
if len(facelist) >= 1:
    for face in facelist:
        x, y, w, h = face
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)


cv2.imshow('arsenal', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[566 138  50  50]
 [228 140  50  50]
 [502 127  50  50]
 [422 128  50  50]
 [ 74 131  50  50]
 [146 132  50  50]
 [338 131  50  50]
 [146 452  50  50]]


In [17]:
?cascade.detectMultiScale